vim.api.nvim_create_autocmd('FileType', {
    pattern = { '<filetype>' },
    callback = function() vim.treesitter.start() end,
})


require('nvim-treesitter').install({
    'awk',
    'bash',
    'bibtex',
    'c',
    'clojure',
    'cmake',
    'css',
    'csv',
    'dockerfile',
    'elixir',
    'erlang',
    'gitignore',
    'go',
    'gomod',
    'gosum',
    'haskell',
    'heex',
    'html',
    'http',
    'java',
    'javadoc',
    'javascript',
    'jq',
    'json',
    'jsx',
    'latex',
    'lua',
    'make',
    'markdown',
    'proto',
    'python',
    'ruby',
    'rust',
    'scheme',
    'sql',
    'ssh_config',
    'supercollider',
    'svelte',
    'tsx',
    'typescript',
    'vue',
    'xml',
    'yaml',
    'zsh'
})
